//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJ.DAL.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int MenuItemId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string DisplayName { get; set; }
        public string Url { get; set; }
        public int MenuItemTypeId { get; set; }
    
        public MenuItemType MenuItemType { get; set; }
    }
}
