//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJ.DependencyInjection {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RJ.DependencyInjection.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve an abstract class or interface..
        /// </summary>
        internal static string CantResolveAbstract {
            get {
                return ResourceManager.GetString("CantResolveAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve dependent type(s) {0}..
        /// </summary>
        internal static string CantResolveDeps {
            get {
                return ResourceManager.GetString("CantResolveDeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register type {0} named {1}. An identical registration exists..
        /// </summary>
        internal static string IdenticalRegistration {
            get {
                return ResourceManager.GetString("IdenticalRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutipule viable constrcutors are available for this type to be constructed by.  Either reduce the number of viable constructors to 1, or register a factory function for the creation of this type..
        /// </summary>
        internal static string MultipleCtors {
            get {
                return ResourceManager.GetString("MultipleCtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutliple registrations exist for the type being resolved.  Either specify the registration name via the [Inject] Attribute, or declare a more specific type to be resolved..
        /// </summary>
        internal static string MultipleRegistrations {
            get {
                return ResourceManager.GetString("MultipleRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve type {0}..
        /// </summary>
        internal static string ResolveDefault {
            get {
                return ResourceManager.GetString("ResolveDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve type named {0}..
        /// </summary>
        internal static string ResolveDefaultNamed {
            get {
                return ResourceManager.GetString("ResolveDefaultNamed", resourceCulture);
            }
        }
    }
}
